development:
  password: shptka_594026290e014c1f2b34359a7019acc6
  theme_id: "142979924122"
  store: checkout-tmc.myshopify.com
  ignore_files:
    - README.md
    - .gitignore
    - config/settings_data.json
    - assets/bundle.js.map
    - locales/
    - "*.png"
    - "*.jpg"  
    - "*.jpeg" 
    - "*.svg" 
    - "*.gif" 
    - "*.mp4"
    - "*.JPG"
    - "*eot"
    - "*woff"
    - "*ttf"
    - "*.js.map"
    - "templates/*.json"